language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t syglee7/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true syglee7/react-test-app npm run test

after_success:
  - docker build -t syglee7/docker-frontend ./frontend
  - docker build -t syglee7/docker-backend ./backend
  - docker build -t syglee7/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push syglee7/docker-frontend
  - docker push syglee7/docker-backend
  - docker push syglee7/docker-nginx